import sys

if len(sys.argv) != 10:
    print 'Parameter error!'
    sys.exit(1)
    
fout = open('output.html', 'w')
fout.write('Here we compute the Elo ratings of all the gomoku AIs which have ever taken part in gomocup, based on the historical competition results (2000 - present). An AI would has a formal general rating only if there exist at least 100 game records for it (This threshold is 50 for freestyle ratings, 100 for fastgame ratings and 20 for standard and renju ratings).\n')
fout.write('\n')
fout.write('<strong>The Gomoku Rating:\n')
fout.write('\n')
fout.write('<strong><a href="#elo_1">The Freestyle Rating (Best Versions Only)</a>\n')
fout.write('<a href="#elo_2">The Fastgame Rating (Best Versions Only)</a>\n')
fout.write('<a href="#elo_3">The Standard Rating (Best Versions Only)</a>\n')
#fout.write('<a href="#elo_4">The General Rating (Best Versions Only)</a></strong>\n')
fout.write('\n')
fout.write('<a href="#elo_5">The Freestyle Rating (All Versions)</a>\n')
fout.write('<a href="#elo_6">The Fastgame Rating (All Versions)</a>\n')
fout.write('<a href="#elo_7">The Standard Rating (All Versions)</a>\n')
#fout.write('<a href="#elo_8">The General Rating (All Versions)</a>\n')
fout.write('\n')
fout.write('<strong>The Renju Rating:\n')
fout.write('\n')
fout.write('<strong><a href="#elo_9">The Renju Rating (All Versions)</a>\n')
fout.write('\n')
fout.write('<a id="elo_1"></a>The Freestyle Rating:\n')
fin = open(sys.argv[1], 'r')
fout.write(fin.read())
fin.close()
fout.write('<a id="elo_2"></a>The Fastgame Rating:\n')
fin = open(sys.argv[2], 'r')
fout.write(fin.read())
fin.close()
fout.write('<a id="elo_3"></a>The Standard Rating:\n')
fin = open(sys.argv[3], 'r')
fout.write(fin.read())
fin.close()
'''
fout.write('<a id="elo_4"></a>The General Rating (Freestyle, Fastgame, Standard):\n')
fin = open(sys.argv[4], 'r')
fout.write(fin.read())
fin.close()
'''
fout.write('<a id="elo_5"></a>The Complete Freestyle Rating:\n')
fin = open(sys.argv[5], 'r')
fout.write(fin.read())
fin.close()
fout.write('<a id="elo_6"></a>The Complete Fastgame Rating:\n')
fin = open(sys.argv[6], 'r')
fout.write(fin.read())
fin.close()
fout.write('<a id="elo_7"></a>The Complete Standard Rating:\n')
fin = open(sys.argv[7], 'r')
fout.write(fin.read())
fin.close()
'''
fout.write('<a id="elo_8"></a>The Complete General Rating (Freestyle, Fastgame, Standard):\n')
fin = open(sys.argv[8], 'r')
fout.write(fin.read())
fin.close()
'''
fout.write('<a id="elo_9"></a>The Complete Renju Rating:\n')
fin = open(sys.argv[9], 'r')
fout.write(fin.read())
fin.close()
fout.write('All ratings are calculated using <a href="http://www.remi-coulom.fr/Bayesian-Elo/">Bayesian Elo</a> with eloAdvantage = 0, eloDraw = 0.01, and default prior.\n')
fout.write('The Elo ratings for gomoku and renju rules are from different rating systems, and should not be compared directly.\n')
fout.close()